sudo: false

language: node_js


node_js:
  - 6
  - 8
  - stable


before_install: curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y && export PATH=./node_modules/.bin:$PATH

script: npm install -g neon-cli && node test 

after_success: npm i codecov && codecov