sudo: false

language: 
  - node_js
  - rust

rust:
  - stable

node_js:
  - 6
  - 8
  - stable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python2.7

script: npm install -g neon-cli && node test 

after_success: npm i codecov && codecov