sudo: true

language: node_js


node_js:
  - 6
  - 8
  - stable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python2.7

script: curl -o rustup.sh https://sh.rustup.rs && sudo sh rustup.sh -y && sudo npm install -g neon-cli && node test 

after_success: npm i codecov && codecov