sudo: required

language: node_js


node_js:
  - 6
  - 8
  - stable


before_install: curl -o rustup.sh https://sh.rustup.rs && sudo sh rustup.sh -y

script: npm install -g neon-cli && node test 

after_success: npm i codecov && codecov