[package]
name = "temp"
version = "0.1.0"
authors = ["zy445566 <zyct@vip.qq.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "temp"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
